name: hello, word

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: rodando um script
      run: echo Hello, Word !
      
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'cassems.com.br'
    needs: build  
    steps:
    - name: rodando um script
      run: echo Deploy dev 
      
  deploy-homol:
    runs-on: ubuntu-latest
    environment:
      name: homol
      url: 'cassems.com.br'
    needs: deploy-dev  
    steps:
    - name: rodando um script
      run: echo Deploy homol
      
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'cassems.com.br'
    needs: deploy-homol
    steps:
    - name: rodando um script
      run: echo Deploy prd   
      
      
      
      
