name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Autenticar no dokcer hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Contruindo imagem Docker
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            nilozjr/teste-kube-news:V1
            nilozjr/teste-kube-news:latest
