name: runs-on

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux,windows]

    steps:
    - name: rodando um script
      run: echo Runs-on no servidor local LINUX
