name: runs-on

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-local, windows-local]

    steps:
    - name: rodando um script
      run: echo Runs-on no servidor local LINUX
